### PR TITLE
Add more terms

### PR DESCRIPTION
**Pull request by stevemk14ebr**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Added english terms

* slave
* slaves
* blackhat
* whitehat
* man hours

### CODE REVIEW

**Comment by wooorm** [comment]
Can you run `npm test` locally? That should generate some code!

**Comment by stevemk14ebr** [comment]
I receive the following error after `npm install` and `npm test`:

```
> retext-equality@6.4.0 test
> npm run generate && npm run build && npm run format && npm run test-coverage


> retext-equality@6.4.0 generate
> node script/generate.js

file:///home/steve/retext-equality/script/generate.js:127
      throw new Error('Refrain from multiple entries:\n  ' + phrases[offset])
            ^

Error: Refrain from multiple entries:
  man hours
    at file:///home/steve/retext-equality/script/generate.js:127:13
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
npm ERR! code 1
npm ERR! path /home/steve/retext-equality
npm ERR! command failed
npm ERR! command sh -c node script/generate.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2021-11-10T19_20_38_338Z-debug.log
npm ERR! code 1
npm ERR! path /home/steve/retext-equality
npm ERR! command failed
npm ERR! command sh -c npm run generate && npm run build && npm run format && npm run test-coverage

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2021-11-10T19_20_38_352Z-debug.log
```

**Comment by stevemk14ebr** [comment]
Ok done. I added a console log too in the generator since the exception didn't actually mention the phrase name that is a duplicate in the error. This showed me that my addition of `man hours` was a duplicate, so that was removed too.

**Comment by wooorm** [comment]
I don’t get the `console.log`? It’s the same `phrases[index]` as shown in the error? 🤔

**Comment by stevemk14ebr** [comment]
> 
> 
> I don’t get the `console.log`? It’s the same `phrases[index]` as shown in the error? 🤔

I am dumb and didn't see the next line:
```
       throw new Error('Refrain from multiple entries:\n  ' + phrases[offset])
            ^

Error: Refrain from multiple entries:
  man hours   <------ misssed this
```

 Will remove

**Review by wooorm — APPROVED** [review]

**Comment by stevemk14ebr** [comment]
If a release could be done before end of day it would help my personal timeline

**Comment by wooorm** [comment]
released, thanks!

**Pull request merged**
