### PR TITLE
Add `man`

### PR DESCRIPTION
**Pull request by Utkarsh299-tech**
Added 'man' to "gals-men"

 Yes, I've seen both the support and contributing docs.

### CODE REVIEW

**Comment by wooorm** [comment]
Hi! Thanks for working on this. The group on L43, which you changed, contains plurals. The group on L59 contains singulars: I think `man` should go in that group instead!

**Comment by Utkarsh299-tech** [comment]
> Hi! Thanks for working on this. The group on L43, which you changed, contains plurals. The group on L59 contains singulars: I think `man` should go in that group instead!

Hi! Yes, thanks for the correction. I've made the required changes as you suggested.

**Review by dumbcoder7 — APPROVED** [review]

**Review by dumbcoder7 — COMMENTED** [review]
Hey Utkarsh, this works well however, the word `boys` is also not flagged by the bot whereas `girls` is. Could you also add that functionality here?

**Comment by Utkarsh299-tech** [comment]
> Hey Utkarsh, this works well however, the word `boys` is also not flagged by the bot whereas `girls` is. Could you also add that functionality here?

Yes, thanks for approving the changes, @dumbcoder7. I will try adding that functionality too.

**Comment by eddiejaoude** [comment]
Great collaboration 👍 - looking forward to getting these improvements 🤓

**Comment by Utkarsh299-tech** [comment]
> Great collaboration 👍 - looking forward to getting these improvements 🤓

Yes, thank you 😀

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks all, released in [5.6.0](https://github.com/retextjs/retext-equality/releases/tag/5.6.0)!

**Pull request merged**
