### PR TITLE
Added a whole lot of notes

### PR DESCRIPTION
**Pull request by AhmedRedaAmin**
Finally all those years on 4Chan were put to use , I enjoyed updating the edge-case slurs greatly :smile: 
get-alex/alex#219

### CODE REVIEW

**Comment by AhmedRedaAmin** [comment]
Oh okay , I 'll see what's happening

**Comment by AhmedRedaAmin** [comment]
Okay , I might need help figuring out what's the problem here , I will attempt removing all changes not related to notes specifically

**Comment by jenweber** [comment]
@AhmedRedaAmin since you added some new alternatives, you need to list them in the test code as well. The tests are failing because they return the full list of alternative phrases. Run `npm test` and you'll see the mismatch, or look at the "Details" and the results of the test on Travis.

```

**Comment by AhmedRedaAmin** [comment]
Oh thanks so much Jen @jenweber  , I wasn't paying attention to the test cases and that I altered your code , does that mean  , I should write new test cases for completely new entries as well ?
I'm down with that tbh , all I'm interested in is not ruining your test coverage .
I ' m force pushing some stuff btw so I have to close the request now :smile:

**Comment by jenweber** [comment]
Hi @AhmedRedaAmin, if you make changes to the codebase or add features, it’s normal to have to change the tests. Please add new test cases for new entries too. I’m just helping out with this project a little, but I always appreciate it for the other projects I maintain :)

**Comment by wooorm** [comment]
Yup, the most important thing is that the tests don’t fail; and after that, that new tests are added. For something small like a `note` that’s less needed, but for a new thing to catch it’s always nice.

And finally: you can keep a PR open, even if you force push some changes! It depends on what you did though, but it should just work™️

**Pull request closed without merging**
